% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jun-2021 19:02:18
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('perceptron1.mat');

ans = [1 1];

bias = -1;

net = saveVarsMat.net; % <1x1 network> unsupported class

output = [1 1 1 0];

p = ...
  [1 1 0 0;
   1 0 1 0];

t = [1 1 1 0];

clear saveVarsMat;
